# -*- coding: utf-8 -*-
"""paap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PewTYUZcv-W3vvaQrJArQrOk21qlgMiD
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Load the model
model = joblib.load('rf_model.pkl')

# Define regions and counties
regions = ['Coast', 'Eastern', 'Nairobi', 'North Eastern', 'Nyanza', 'Rift Valley', 'Western']
county_region_map = {
    'Coast': ['Mombasa', 'Kwale', 'Kilifi', 'Tana River', 'Lamu', 'Taita-Taveta'],
    'Eastern': ['Machakos', 'Makueni', 'Kitui', 'Embu', 'Meru', 'Isiolo', 'Tharaka-Nithi'],
    'Nairobi': ['Nairobi'],
    'North Eastern': ['Garissa', 'Wajir', 'Mandera'],
    'Nyanza': ['Kisumu', 'Siaya', 'Homa Bay', 'Migori', 'Kisii', 'Nyamira'],
    'Rift Valley': ['Uasin Gishu', 'Elgeyo-Marakwet', 'Nandi', 'Baringo', 'Laikipia', 'Nakuru', 'Narok', 'Kajiado', 'Kericho', 'Bomet', 'Samburu', 'Turkana', 'West Pokot'],
    'Western': ['Kakamega', 'Vihiga', 'Bungoma', 'Busia'],
}

# User input widgets
st.title('Maize Price Prediction')

region = st.selectbox('Select Region', regions)
county = st.selectbox('Select County', county_region_map[region])
year = st.slider('Select Year', 2024, 2030, 2025)
month = st.slider('Select Month', 1, 12, 1)

# Prepare input data
def prepare_input_data(region, county, year, month):
    input_data = {
        'Year': year,
        'Month': month,
        'Annual Temperature': 25,  # Replace with average or actual data
        'Annual Rainfall': 1000,   # Replace with average or actual data
        'Amount Produced(Tonnes)': 5000,  # Replace with average or actual data
        f'County_{county}': 1,
        f'Region_{region}': 1
    }

    # Add missing columns as 0
    for col in features:
        if col not in input_data:
            input_data[col] = 0

    return pd.DataFrame([input_data])

# Prediction
if st.button('Predict Price'):
    input_df = prepare_input_data(region, county, year, month)
    predicted_price = model.predict(input_df[features])[0]
    st.write(f'Predicted Price for {county}, {region} in {year}-{month}: {predicted_price:.2f} KES')

# Define features used in the model
features = ['Year', 'Month', 'Annual Temperature', 'Annual Rainfall', 'Amount Produced(Tonnes)']
for region in regions:
    features.append(f'Region_{region}')
    for county in county_region_map[region]:
        features.append(f'County_{county}')
